# Generated by Django 4.1.4 on 2022-12-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0016_alter_new_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.user')),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'managed': False, 'verbose_name': 'Biz haqimzda', 'verbose_name_plural': 'Biz haqimzda'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': "O'quv kurs", 'verbose_name_plural': "O'quv kurslar"},
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_en',
        ),
        migrations.RemoveField(
            model_name='new',
            name='text_en',
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='\\images'),
        ),
        migrations.AlterModelTable(
            name='about',
            table='about_as',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugc.product')),
            ],
        ),
    ]
