# Generated by Django 4.1.4 on 2022-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0017_order_alter_about_options_alter_new_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'managed': False, 'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AddField(
            model_name='new',
            name='heading_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='about',
            table='about_us',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
