# Generated by Django 4.1.4 on 2022-12-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0018_remove_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': "O'quv kurs", 'verbose_name_plural': "O'quv kurslar"},
        ),
    ]
